# Generated by Django 5.0.6 on 2024-06-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
