# Generated by Django 5.0.6 on 2024-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_total_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='api_categor_store_i_cd2a5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='county',
            name='api_county_store_i_735e6e_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.RemoveField(
            model_name='county',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stores', to='api.category'),
        ),
        migrations.AddField(
            model_name='store',
            name='counties',
            field=models.ManyToManyField(blank=True, related_name='stores', to='api.county'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['name'], name='api_county_name_5d5d13_idx'),
        ),
    ]
