name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Replace with your actual test command

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Deploy to Render
        run: |
          render deploy -- --env-file .env.prod
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_DEPLOY_KEY }}

      - name: Test deployment
        run: